//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroFood.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonDatHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonDatHang()
        {
            this.CTDonDatHangs = new HashSet<CTDonDatHang>();
        }
    
        public string MaDDH { get; set; }
        public string MaKH { get; set; }
        public System.DateTime NgayDH { get; set; }
        public System.DateTime NgayGH { get; set; }
        public string TenNguoiNhan { get; set; }
        public string DiaChiNhan { get; set; }
        public string SDTNhanHang { get; set; }
        public string HTThanhToan { get; set; }
        public string HTGiaoHang { get; set; }
        public int TriGia { get; set; }
        public string TinhTrang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDonDatHang> CTDonDatHangs { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
